---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nvidia-gpu-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/nvidia-gpu-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nvidia-gpu-operator
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
