---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 4.1.4
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    configuration:
      backupStorageLocation:
        - name: default
          bucket: velero
          provider: aws
          default: true
          config:
            region: us-east-1
            s3ForcePathStyle: true
            s3Url: https://s3.truenas.${SECRET_DOMAIN_LOCAL}
      fsBackupTimeout: 6h
      features: EnableCSI
      defaultVolumesToFsBackup: true

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.7.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:v0.5.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    credentials:
      existingSecret: velero-truenas-secret

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    backupsEnabled: true
    snapshotsEnabled: false

    upgradeCRDs: true
    cleanUpCRDs: false

    deployNodeAgent: true
    nodeAgent:
      podVolumePath: /var/lib/kubelet/pods
      privileged: true
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi

    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
