apiVersion: v1
kind: Secret
metadata:
    name: velero-truenas-secret
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:RTpN2LXBYrqTSj+HoT5WLZBbApPjikPIiZFwhf9+IxeAlK3eVQxaGRyPbvMlP2WYbzaII4HyxBmC3tSQRCspMV1KbnP8axWZBypMNCJQ7FaL3ai5sCs228ySqTInAujwkuP2ZR33fmZ6AVSJz5A4,iv:E2HC9V2czIpBRl37P2kk3641kdceIE+3rdmMguQ9Uik=,tag:JWdjWlnulnpg9v4YkAcgdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSG9HL1QyQW0zWWVDOG10
            YW5CcUxuMTU1UzFRT1NNalFPNVNuck5KZTNjCnZya25uYzdwQ2lYU045NHoyMFdB
            aU5RVWQ5TllRRElCQ0FLMmNpSHd1MzAKLS0tIEM4b3pBeTAzS2FEV251K3VDT3Rx
            UmZibUxDbk1xQlNZbGNiZWRSa1F0M2cKenWsBFwVHgNFQeZdouH+Acs1jffzxaxs
            P9iCdNsgaVUAT2A3L+d4L3vSIxtjy7+y7XxerLVOlCt4p4aOaSe7UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-18T02:19:59Z"
    mac: ENC[AES256_GCM,data:vYvqFjLTRADVPywZqCAJGt8EKezq1G/ppy/x22BT6NWw28YNGNXPKAEP/kEf8Apia1+eoE+3EBouBuIk7e4O2zoei6uvA0Z4HE3ZOfMD3PjTqyuES1hbKcaRTzzb0mEdPgl8rlGcrAXk0kAFMJtV6VRhgds8aHNdpwEYoH1TuZI=,iv:jR2TuYSAOByj6sGRIgpxyUqk67QE7b2WKccNX48ka5Y=,tag:tI/eSogscTv2UPhZ0h3CTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
