---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2023.8.4@sha256:60777ed79b9cde58621c83fcb8ce8d4d4654bbe65cfeb048b4f5afe91fb407ac

    hostNetwork: true
    podAnnotations:
      k8s.v1.cni.cncf.io/networks: |
        [{
          "name":"multus-bridge",
          "namespace": "networking",
          "ips": ["192.168.1.201/20"]
        }]

    env:
      HASS__PORT: &port 8123
      HASS__APPLICATION_URL: &host "ha.${SECRET_DOMAIN_LOCAL}"

    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          io.cilium/lb-ipam-ips: "${HOME_ASSISTANT_ADDR}"
        ports:
          http:
            port: *port

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config

    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100

    resources:
      requests:
        cpu: 22m
        memory: 512M
      limits:
        memory: 819M
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.16.1
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: &host "haconfig.${SECRET_DOMAIN_LOCAL}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
        volumeMounts:
          - name: config
            mountPath: /config
