kind: ENC[AES256_GCM,data:Jn1U4qZ7,iv:2+nXZW22wkAmvtilOXlI4c0YNmJrPHBg93CufGeHyYo=,tag:Zo4GYwf/kxM85E8YEuNesw==,type:str]
ansible_user: ENC[AES256_GCM,data:M8x1H6FQ,iv:YZBvVcF/Ppt76gy+HIEE1YwAtWS18j0rruaCP36PO4o=,tag:2R4q8vUiDw8Q7Nowail0nA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:7yh+gAEx5TlOEoda53kNr2U0NSY=,iv:Rslu/VWNpB08+zmrNI6FnJ0d3JHK6JerythcrWARgKE=,tag:oDM2Pyr7KskeGcXEH1wfpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrN0MwUmdEZlFzb2FlZEpK
            blRtT01uWFptaGhLMUpJZ2dPbCt3Nlg0TVdRCmZVQ05XR0R1eEdpRXNLcGN3YnBW
            TEg0U3dITVRFcW1vdmdqQTYxbGxCT0UKLS0tIFRUZTUyNStMbStWcURDZlBiaTZL
            a1h5SFBOQlB1VnVMSndkTUF3OFp1WjgKlBAEBO09tm7yWPNCPrOPeI3gYPYCJTBQ
            j3bh9U2fy50R2nanxPUDXK9vVxQyeuO6OqvoLLgjKB3kO3LOBLJZ6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-25T04:18:53Z"
    mac: ENC[AES256_GCM,data:yN+1D4WLMo4e08nJ8kw/MfYd+ztOZH1KULghBV/qor8DYCEk7VPMJVMOGoM1scQLGwEq+4fJYa+JH+3AYNtLu7swcMFNxqBt3+NjFeMxxF8+S2JQmF8F1Alxvgila03tlMKsQF/BK4t0AsFBY8aPJc7r6cWcE7XaopI9f27EFxE=,iv:LLMClCh13+1HiL08kNwB+7eiir8p1KlF9FslL7Zf2Ns=,tag:ef2Sur5Qf8rMQlJk+TXSfQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
