kind: ENC[AES256_GCM,data:mn8BuFwu,iv:U1eacGCGi3zTkymfiFwPjER+yaxh2nNZlPekYVn9PB4=,tag:I51FHm3lkKyhPW3g2n2x8w==,type:str]
ansible_user: ENC[AES256_GCM,data:zQI4k+5r,iv:/ahCbdHHcTvAKnnNOAn+ZINkghwPSn8ghHsw/59AJP0=,tag:Y9yelFbCRMRElz2rti1Tvg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Ih69OayATM8/WTNqeRRGS+OIFxY=,iv:Df3I3uaE60Kou3jV4/gWkuuCJbz8Cikzx3RaBXWvxFs=,tag:fzlNFqWulieNQnbEwBY5oQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdUlGV3llQjMrMXdrSEtu
            VVlyNXVUM1pEdzliMVRXZ1FyS3VkUG9wTGhnCmZoMFZDM1JZaUVXOHJaWCtKdzJz
            NDBoYWQvSlZ4dTF4RjJvckQxKzhWWDgKLS0tIGUvdWFZOHF4S2hhSkx1YW9sSVp6
            ZUhJVWRYVVRQVDY3QkUzWjhoRVIxUWMKeFKs2uVme3ajtfqnV/fIgXgkVy/b6MMr
            j4J+63V+pUFzstAHU5jVvbhGU0XD3n+URFpgaMMaBNuTd7j2TlfLTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-25T04:19:05Z"
    mac: ENC[AES256_GCM,data:JAtQT2LH3IQ+3prfIeOjPVPtK4awLjMojEeUEjZw9OQdjwI/x281YN8VepLkzqtlZJjAtJumE9VvrCMT07eFDBD712jnWFFuiUv6jEjHQi5iCnoEH6mgHIW8B6cqWk+AaPw3NEc1tSs9/9qZPamzhVWkiRtKKRZ4QcxVHTy9eeI=,iv:5mGoSwrkETND+zFA+a+jLdPEWZFT2Uq5dwR+IRxcrk4=,tag:WjQFTV5S9Qq8XmXWhOIPow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
