---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-ingress-certificates
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/external-ingress/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-external-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
    - name: cluster-apps-external-ingress-certificates
  path: ./kubernetes/apps/networking/external-ingress/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
