---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  values:
    hajimari:
      title: Hajimari - Application Dashboard
      darkTheme: espresso
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: true
      showAppStatus: true
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - flux-system
          - media
          - monitoring
          - networking
          - downloads
          - rook-ceph
    customApps:
      - group: External Services
        apps:
          - name: TrueNAS SCALE
            url: truenas.${SECRET_DOMAIN_LOCAL}
            icon: simple-icons:truenas
          - name: MinIO
            url: truenas.${SECRET_DOMAIN_LOCAL}
            icon: mdi:bucket-plus-outline
          - name: PiHole
            url: pihole.${SECRET_DOMAIN_LOCAL}
            icon: simple-icons:pihole
          - name: Calvin
            url: calvin.proxmox.${SECRET_DOMAIN_LOCAL}
            icon: cib:proxmox
          - name: Hobbes
            url: calvin.proxmox.${SECRET_DOMAIN_LOCAL}
            icon: cib:proxmox
          - name: Susie
            url: calvin.proxmox.${SECRET_DOMAIN_LOCAL}
            icon: cib:proxmox

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host apps.${SECRET_DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
