---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-multus
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/networking/multus/app"
  prune: true
  healthChecks:
    - kind: HelmRelease
      name: multus
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-multus-config
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/networking/multus/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-multus
