{
 "title": "TrueNAS 12 (VictoriaMetrics data source)",
 "description": "TrueNAS 12 dashboard using official Graphite export to a Prometheus data source.",
 "tags": [
  "FreeNAS",
  "TrueNAS"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "FreeNAS Server",
    "query": "{__graphite__=\"servers.*.aggregation-cpu-average.cpu-idle\"}"
   },
   {
    "name": "network_interface",
    "label": "Network Interface",
    "query": "{__graphite__=\"servers.*.interface-*.if_octets.tx\"}"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "{__graphite__=\"servers.*.cpu-*.cpu-idle\"}"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "{__graphite__=\"servers.*.disk-*.disk_octets.read\"}"
   },
   {
    "name": "mount",
    "label": "Mount",
    "query": "{__graphite__=\"servers.*.df-*.df_complex-used\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Load 1min",
   "type": "singlestat",
   "description": "Quicknum, Load 1min",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "{__graphite__=\"servers.$server.load.load.shortterm\"}",
     "legendFormat": "$server",
     "target": "aliasByNode(servers.$server.load.load.shortterm,1,3)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime as an easily readable number",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "{__graphite__=\"servers.$server.uptime.uptime\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.uptime.uptime"
    }
   ]
  },
  {
   "title": "ZFS ARC Hit Ratio",
   "type": "singlestat",
   "description": "Quicknum, Load 1min",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "{__graphite__=\"servers.$server.zfs_arc_v2.arcstat_ratio_arc-hits\"}",
     "legendFormat": "$server",
     "target": "aliasByNode(servers.$server.zfs_arc_v2.arcstat_ratio_arc-hits, 1)"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "System Load",
   "type": "graph",
   "description": "1, 5 and 15 minute average load. Basically number of processes that have wanted to run per second with some averaging and decay to show load history.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.load.*.*\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]load[.]load[.]([^.]+)\")",
     "legendFormat": "{{legend}}",
     "target": "aliasByNode(servers.$server.load.*.*, 1,4)"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "description": "CPU temperatures in Celsius",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.cputemp-$cpu.temperature\"}, \"legend\", \"$1.cpu$2\", \"__name__\", \"servers[.]([^.]+)[.]cputemp-([0-9]+).temperature\")/10-273.15",
     "legendFormat": "{{legend}}",
     "target": "aliasByNode(scale(offset(servers.$server.cputemp-$cpu.*,-2731.5),0.1),1,2)"
    }
   ]
  },
  {
   "title": "ZFS ARC Hit Ratio",
   "type": "graph",
   "description": "ARC is ZFS in-memory cache, hit ratio should be between 90-100%. If not, you may need more memory.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.zfs_arc_v2.arcstat_ratio_arc-hits\"}, \"legend\", \"$1\", \"__name__\", \"servers[.]([^.]+).*\")",
     "legendFormat": "{{legend}}",
     "target": "aliasByNode(servers.$server.zfs_arc_v2.arcstat_ratio_arc-hits, 1)"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "graph",
   "description": "Time between reboots",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.uptime.uptime\"}, \"legend\", \"$1\", \"__name__\", \"servers[.]([^.]+).*\")",
     "legendFormat": "{{legend}}",
     "target": "aliasByNode(servers.$server.uptime.uptime,1)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU Usage per CPU. Max is 100% or 100% times number of CPUs depending on FreeNAS setting System -> Advanced -> Report CPU usage in percentage. If your number is >100,  set that flag in FreeNAS.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.cpu-$cpu.*\"}, \"legend\", \"$1.$2.$3\", \"__name__\", \"servers[.]([^.]+)[.](cpu-[0-9]+)[.]cpu-([^.]+).*\")",
     "legendFormat": "{{legend}}",
     "target": "aliasByNode(servers.$server.cpu-$cpu.*,1,3)"
    }
   ]
  },
  {
   "title": "Aggregation CPU Average",
   "type": "graph",
   "description": "CPU Usage across all CPUs. Max is 100% or 100% times number of CPUs(?) depending on FreeNAS setting System -> Advanced -> Report CPU usage in percentage. If your number is >100,  set that flag in FreeNAS.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.aggregation-cpu-average.*\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]aggregation-cpu-average[.]([^.]+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.aggregation-cpu-average.*,1,3)"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "description": "Number of processes",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.processes.*\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]processes[.]ps_state-([^.]+)\")",
     "legendFormat": "{{legend}}",
     "target": "aliasByNode(servers.$server.processes.*,1,3)"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "description": "Swap on system",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.swap.swap-used\"}, \"legend\", \"$1\", \"__name__\", \"servers[.]([^.]+).*\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.swap.swap-used"
    },
    {
     "expr": "label_replace({__graphite__=\"servers.$server.swap.swap-free\"}, \"legend\", \"$1\", \"__name__\", \"servers[.]([^.]+).*\")",
     "legendFormat": "{{legend}}",
     "target": "servers.$server.swap.swap-free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Wired memory is kernel usage and will be very high because ZFS runs in kernel space and its cache etc is included in this number.  Default ZFS usage is 80% of total mem, configurable but leave it.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.memory.*\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]memory[.]memory-([^.]+)\")",
     "legendFormat": "{{legend}}",
     "target": "aliasByNode(servers.$server.memory.*,1,3)"
    }
   ]
  },
  {
   "title": "Network packets",
   "type": "graph",
   "description": "Number of network packets",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.interface-$network_interface.if_packets.tx\"}, \"legend\", \"$1.$2.$3\", \"__name__\", \"servers[.]([^.]+)[.]interface-([^.]+)[.]if_packets[.]([^.]+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.interface-$network_interface.if_packets.tx,1,2,4)"
    },
    {
     "expr": "-label_replace({__graphite__=\"servers.$server.interface-$network_interface.if_packets.rx\"}, \"legend\", \"$1.$2.$3\", \"__name__\", \"servers[.]([^.]+)[.]interface-([^.]+)[.]if_packets[.]([^.]+)\")",
     "legendFormat": "{{legend}}",
     "target": "scale(aliasByNode(servers.$server.interface-$network_interface.if_packets.rx,1,2,4),-1)"
    }
   ]
  },
  {
   "title": "Network bytes",
   "type": "graph",
   "description": "Network R/W bytes per second",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.interface-$network_interface.if_octets.tx\"}, \"legend\", \"$1.$2.$3\", \"__name__\", \"servers[.]([^.]+)[.]interface-([^.]+)[.]if_octets[.]([^.]+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.interface-$network_interface.if_octets.tx,1,2,4)"
    },
    {
     "expr": "-label_replace({__graphite__=\"servers.$server.interface-$network_interface.if_octets.rx\"}, \"legend\", \"$1.$2.$3\", \"__name__\", \"servers[.]([^.]+)[.]interface-([^.]+)[.]if_octets[.]([^.]+)\")",
     "legendFormat": "{{legend}}",
     "target": "scale(aliasByNode(servers.$server.interface-$network_interface.if_octets.rx,1,2,4),-1)"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "description": "Network R/W Errors. Should not happen.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.interface-$network_interface.if_errors.tx\"}, \"legend\", \"$1.$2.$3\", \"__name__\", \"servers[.]([^.]+)[.]interface-([^.]+)[.]if_errors[.]([^.]+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.interface-$network_interface.if_errors.*,1,2,4)"
    },
    {
     "expr": "-label_replace({__graphite__=\"servers.$server.interface-$network_interface.if_errors.rx\"}, \"legend\", \"$1.$2.$3\", \"__name__\", \"servers[.]([^.]+)[.]interface-([^.]+)[.]if_errors[.]([^.]+)\")",
     "legendFormat": "{{legend}}",
     "target": "scale(aliasByNode(servers.$server.interface-$network_interface.if_errors.*,1,2,4),-1)"
    }
   ]
  },
  { "title": "Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk percent busy",
   "type": "graph",
   "description": "How much of the time does the disk have a request active or pending",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.geom_stat.geom_busy_percent-$disk\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]geom_stat[.]geom_busy_percent-([^.]+)\")",
     "legendFormat": "{{legend}}",
     "target": "aliasByNode(servers.$server.geom_stat.geom_busy_percent-$disk,1,3)"
    }
   ]
  },
  {
   "title": "Disk Operations/s (?)",
   "type": "graph",
   "description": "Unsure what this is exactly since there is a RWD metric on the same.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.geom_stat.geom_ops-$disk\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]geom_stat[.]geom_ops-([^.]+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.geom_stat.geom_ops-$disk,1,3)"
    }
   ]
  },
  {
   "title": "Disk RWD Operations/s (?)",
   "type": "graph",
   "description": "Unsure what this exactly",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.geom_stat.geom_ops_rwd-$disk.*\"}, \"legend\", \"$1.$2.$3\", \"__name__\", \"servers[.]([^.]+)[.]geom_stat[.]geom_ops_rwd-([^.]+)[.]([^.]+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.geom_stat.geom_ops_rwd-$disk.*,1,3)"
    }
   ]
  },
  {
   "title": "Disk Bandwidth(?)",
   "type": "graph",
   "description": "Unsure what BW means here,  potentially bandwidth i.e. number of Bytes/s",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.geom_stat.geom_bw-$disk.*\"}, \"legend\", \"$1.$2.$3\", \"__name__\", \"servers[.]([^.]+)[.]geom_stat[.]geom_bw-([^.]+)[.]([^.]+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.geom_stat.geom_bw-$disk.*,1,3)"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "description": "How long does the disk time to fulful a request",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.geom_stat.geom_latency-$disk.*\"}, \"legend\", \"$1.$2.$3\", \"__name__\", \"servers[.]([^.]+)[.]geom_stat[.]geom_latency-([^.]+)[.]([^.]+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.geom_stat.geom_latency-$disk.*,1,3,4)"
    }
   ]
  },
  {
   "title": "Disk Queue",
   "type": "graph",
   "description": "How many disk requests are there in the queue",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.geom_stat.geom_queue-$disk\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]geom_stat[.]geom_queue-([^.]+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.geom_stat.geom_queue-$disk,1,3)"
    }
   ]
  },
  {
   "title": "Disk Temperatures",
   "type": "graph",
   "description": "Disk temperatures. Not all disks/controllers will report this.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.disktemp-$disk.temperature\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]disktemp-([^.]+).temperature\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.disktemp-$disk.temperature,1,2)"
    }
   ]
  },
  {
   "title": "Filesystem Free",
   "type": "graph",
   "description": "Available memory on all filesystems",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.df-$mount.df_complex-free\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]df-([^.]+)[.]df_complex-free\")",
     "legendFormat": "{{legend}}",
     "target": "aliasByNode(servers.$server.df-$mount.df_complex-free,1,2)"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "description": "Lists free, reserved and used space on available filesystems",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.df-$mount.df_complex-used\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]df-([^.]+)[.]df_complex-used\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(servers.$server.df-$mount.*,1,2,3)"
    }
   ]
  },
  { "title": "Technical details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CTL IOCTL",
   "type": "graph",
   "description": "CTL - CAM Target Layer stuff",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.ctl-ioctl.*.*\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]ctl-ioctl[.](.+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.ctl-ioctl.*.*"
    }
   ]
  },
  {
   "title": "CTL TPC",
   "type": "graph",
   "description": "CTL - CAM Target Layer stuff",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.ctl-tpc.*.*\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]ctl-tpc[.](.+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.ctl-tpc.*.*"
    }
   ]
  },
  {
   "title": "ZFS ARC complete",
   "type": "graph",
   "description": "All the ZFS ARC (in-memory ZFS cache) in one place",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.zfs_arc.*\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]zfs_arc[.](.+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.zfs_arc.*"
    }
   ]
  },
  {
   "title": "ZFS ARC v2 complete",
   "type": "graph",
   "description": "All the ZFS ARC v2 measurements in one place.  Unsure if this is newer or complimentary to the ZFS ARC measurements.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__graphite__=\"servers.$server.zfs_arc_v2.*\"}, \"legend\", \"$1.$2\", \"__name__\", \"servers[.]([^.]+)[.]zfs_arc_v2[.](.+)\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{legend}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.zfs_arc_v2.*"
    }
   ]
  }
 ]
}