---
# currently only supports v1 version
version: v1
volumePolicies:
  # each policy consists of a list of conditions and an action
  # we could have lots of policies, but if the resource matched the first policy, the latters will be ignored
  # each key in the object is one condition, and one policy will apply to resources that meet ALL conditions
  # NOTE: capacity or storageClass is suited for [Persistent Volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes), and pod [Volume](https://kubernetes.io/docs/concepts/storage/volumes) not support it.
  - conditions:
      # nfs could be empty which matches any nfs volume source
      nfs: { }
    action:
      type: skip
