---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: grafana-dashboards
    behavior: create
    files:
      - ./dashboards/loki-dashboard.json
