---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-unpackerr
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-sonarr
    - name: cluster-apps-radarr
  path: ./kubernetes/apps/downloads/unpackerr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: unpackerr
      namespace: downloads
  interval: 30m
  retryInterval: 1m
  timeout: 3m
