---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name pod-gateway-port-forward
  namespace: vpn
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: downloads-gateway
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: ceph-filesystem
