---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-data-all
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${TRUENAS_IP_ADDRESS}"
    path: /mnt/nasty/Media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truenas-data-all
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: truenas-data-all
