---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: tempo
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    tempo:
      searchEnabled: true
      repository: grafana/tempo
      tag: 1.5.0
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 750m
          memory: 750Mi
      retention: 336h
      metricsGenerator:
        enabled: true
      storage:
        trace:
          backend: s3
          s3:
            insecure: true
    persistence:
      enabled: false

    tempoQuery:
      repository: grafana/tempo-query
      tag: 1.4.1

    serviceMonitor:
      enabled: true

  valuesFrom:
    - targetPath: tempo.storage.trace.s3.bucket
      kind: ConfigMap
      name: tempo-bucket
      valuesKey: BUCKET_NAME
    - targetPath: tempo.storage.trace.s3.endpoint
      kind: ConfigMap
      name: tempo-bucket
      valuesKey: BUCKET_HOST
    - targetPath: tempo.storage.trace.s3.access_key
      kind: Secret
      name: tempo-bucket
      valuesKey: AWS_ACCESS_KEY_ID
    - targetPath: tempo.storage.trace.s3.secret_key
      kind: Secret
      name: tempo-bucket
      valuesKey: AWS_SECRET_ACCESS_KEY
