---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vector
      version: 0.24.1
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  dependsOn:
    - name: loki
      namespace: monitoring
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Service
              name: vector-aggregator
            patch:
              - op: replace
                path: /spec/externalTrafficPolicy
                value: Local
  values:
    image:
      repository: timberio/vector
      tag: 0.32.1-debian
    role: Stateless-Aggregator
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      sources:
        journal_logs:
          type: vector
          address: 0.0.0.0:6000
          version: "2"
        kubernetes_logs:
          type: vector
          address: 0.0.0.0:6010
          version: "2"
        vector_metrics:
          type: internal_metrics
      transforms:
        kubernetes_logs_remap:
          type: remap
          inputs:
            - kubernetes_logs
          source: |
            # Standardize 'app' index
            .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
      sinks:
        loki_journal:
          type: loki
          inputs:
            - journal_logs
          endpoint: http://loki-gateway:80
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            hostname: >-
              {{`{{ host }}`}}
        loki_kubernetes:
          type: loki
          inputs:
            - kubernetes_logs_remap
          endpoint: http://loki-gateway:80
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            app: >-
              {{`{{ custom_app_name }}`}}
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            pod: >-
              {{`{{ kubernetes.pod_name }}`}}
            container: >-
              {{`{{ kubernetes.container_name }}`}}
            instance: >-
              {{`{{ kubernetes.pod_labels."app.kubernetes.io/instance" }}`}}
        prom_exporter:
          type: prometheus_exporter
          inputs:
            - vector_metrics
          address: 0.0.0.0:9090
    service:
      enabled: true
      type: LoadBalancer
    podMonitor:
      enabled: true
