---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: public.ecr.aws/docker/library/eclipse-mosquitto
      tag: 2.0.18

    initContainers:
      user-import:
        image: public.ecr.aws/docker/library/eclipse-mosquitto:2.0.18@sha256:cb3afd02611b0c58b328196ab00de0158322b4c1e014841fb182d2a0ea3a79b9
        command:
          - "/bin/sh"
          - -c
        args:
          - /data/mosquitto_init/load-users.sh /data/mosquitto_secret /data/external_config/mosquitto_pwd && mosquitto_passwd -U /data/external_config/mosquitto_pwd && echo "User import Completed"
        volumeMounts:
          - name: mosquitto-secret
            mountPath: /data/mosquitto_secret
          - name: mosquitto-init-config
            mountPath: /data/mosquitto_init
          - name: external-config
            mountPath: /data/external_config

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          io.cilium/lb-ipam-ips: "${MOSQUITTO_ADDR}"
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
            protocol: TCP

    persistence:
      mosquitto-config:
        enabled: true
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
      mosquitto-secret:
        enabled: true
        type: secret
        name: mosquitto-secret
        mountPath: "-"
      mosquitto-init-config:
        enabled: true
        type: configMap
        name: mosquitto-init-config
        mountPath: "-"
        defaultMode: 0755
      external-config:
        enabled: true
        type: emptyDir
        mountPath: /mosquitto/external_config

    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 10Mi

    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
