---

# ssh_authorized_keys: []

ubuntu:
  packages:
    - apt-transport-https
    - ca-certificates
    - conntrack
    - curl
    - dirmngr
    - fish
    - gdisk
    - gnupg
    - hdparm
    - htop
    - iptables
    - iputils-ping
    - ipvsadm
    - libnfs-utils
    - libseccomp2
    - lm-sensors
    - lsscsi
    - multipath-tools
    - nano
    - neofetch
    - net-tools
    - nfs-common
    - nvme-cli
    - open-iscsi
    - parted
    - psmisc
    - python3
    - python3-apt
    - python3-kubernetes
    - python3-yaml
    - scsitools
    - smartmontools
    - socat
    - software-properties-common
    - unzip
    - util-linux
