---
timezone: "America/Los_Angeles"
github_username: "mihirsamdarshi"
coredns_addr: "10.43.0.10"
kube_vip_addr: "192.168.10.100"
cluster_cidr: "10.42.0.0/16"
service_cidr: "10.43.0.0/16"
node_cidr: "192.168.10.0/24"
