---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: downloads-gateway-protonvpn
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              $patch: merge
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: downloads-gateway-protonvpn-pod-gateway
              spec:
                template:
                  spec:
                    containers:
                      - name: gluetun
                        volumeMounts:
                          - name: shared-port
                            mountPath: /var/run/shared_port
                    volumes:
                      - name: shared-port
                        persistentVolumeClaim:
                          claimName: pod-gateway-port-forward

  values:
    image:
      # -- image repository of the gateway and inserted helper containers
      repository: ghcr.io/bjw-s/pod-gateway
      # -- image tag of the gateway and inserted helper containers
      # renovate: datasource=docker imageName=ghcr.io/bjw-s/pod-gateway
      tag: dev@sha256:cb3644a1e8a42b00537c8f9a265bb708a7d43b3382d82f40174bba5eea036449

    # -- The DNSPolicy to apply to the POD. Only when set to "None" will the
    # DNS value above apply. To avoid altering POD DNS (i.e., to allow
    # initContainers to use DNS before the VXLAN is up), set to "ClusterFirst"
    DNS: 172.16.10.1

    routed_namespaces:
      - downloads

    settings:
      # -- IPs not sent to the POD gateway but to the default K8S.
      # Multiple CIDRs can be specified using blanks as separator.
      # Example for Calico: ""172.22.0.0/16 172.24.0.0/16"
      #
      # This is needed, for example, in case your CNI does
      # not add a non-default rule for the K8S addresses (Flannel does).
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16 192.168.0.0/16"
      # -- Vxlan ID to use
      VXLAN_ID: 43
      # -- VXLAN needs an /24 IP range not conflicting with K8S and local IP ranges
      VXLAN_IP_NETWORK: 172.16.10
      # -- Keep a range of IPs for static assignment in nat.conf
      VXLAN_GATEWAY_FIRST_DYNAMIC_IP: 20
      # -- Traffic to these IPs will be sent through the K8S gateway
      VPN_LOCAL_CIDRS: "10.42.0.0/16 10.43.0.0/16 192.168.0.0/16"
      # -- DNS queries to these domains will be resolved by K8S DNS instead of
      # the default (typically the VPN client changes it)
      DNS_LOCAL_CIDRS: "local"

    addons:
      vpn:
        # -- Enable the VPN if you want to route through a VPN.
        # You might also want to set VPN_BLOCK_OTHER_TRAFFIC to true
        # for extra safeness in case the VPN does connect
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: latest@sha256:56af8a2476c2ff57c897fd11d59771d0fc4b9fcc3c2697efaceb66c5aad75662

        env:
          VPN_SERVICE_PROVIDER: custom
          VPN_TYPE: wireguard
          VPN_PORT_FORWARDING_STATUS_FILE: /var/run/shared_port/port
          VPN_INTERFACE: wg0
          UPDATER_PERIOD: "24h"
          FIREWALL: "off"
          DOT: "off"
        envFrom:
          - secretRef:
              name: pod-gateway-secret-protonvpn

        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE

        networkPolicy:
          enabled: false

      netshoot:
        enabled: true

    podAnnotations:
      configmap.reloader.stakater.com/reload: downloads-gateway-pod-gateway
      secret.reloader.stakater.com/reload: pod-gateway-secret-protonvpn

    webhook:
      image:
        # -- image repository of the webhook
        repository: ghcr.io/angelnu/gateway-admision-controller
        # -- image pullPolicy of the webhook
        pullPolicy: IfNotPresent
        # -- image tag of the webhook
        tag: v3.9.0@sha256:4e169da5af107a9c6c784d3e03c89da07fad45f18358ab5b7177662df12d955a

      # -- number of webhook instances to deploy
      replicas: 1

      # -- strategy for updates
      strategy:
        type: RollingUpdate
      # -- Selector for namespace.
      # All pods in this namespace will get evaluated by the webhook.
      # **IMPORTANT**: Do not select the namespace where the webhook
      # is deployed to, or you will get locking issues.
      namespaceSelector:
        type: label
        label: "routed-gateway-protonvpn"

      # -- default behviour for new PODs in the evaluated namespace
      gatewayDefault: true
      # -- label name to check when evaluating POD. If true the POD
      # will get the gateway. If not set setGatewayDefault will apply.
      gatewayLabel: setGateway
      # -- annotation name to check when evaluating POD. If true the POD
      # will get the gateway. If not set setGatewayDefault will apply.
      gatewayAnnotation: setGateway
