---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./networkpolicy.yaml
  - ./secret.sops.yaml
  - ./helmrelease_protonvpn.yaml
  - ./secret_protonvpn.sops.yaml
  - ./manager.yaml
  - ./manager_secret.sops.yaml
  - ./volume.yaml
