apiVersion: v1
kind: Secret
metadata:
    name: port-manager-secret
    namespace: vpn
stringData:
    APPLICATION_HOST: ENC[AES256_GCM,data:25L6y9al+/kXnxF61n6pj5a+0LReHC91E8ZTWIMf44xGxOhd92wI,iv:63P8Z3r+l1TZxVj/857wW21ElXOfIX2+oaCYyQJxeb8=,tag:5/MI+q5f13y//E6R9UdNYw==,type:str]
    APPLICATION_PORT: ENC[AES256_GCM,data:AE01WQ==,iv:HRqzcgzixmXDPs0rDrOPa4CHBMnuO96r08dWCofLLNw=,tag:/6svRBL7Pi+aDCw5EBY2ag==,type:str]
    APPLICATION_USER: ENC[AES256_GCM,data:ZUBr4ck=,iv:5VY67YCazEG/xqVoRGV4oSt32EQ1R3i4pJUQPFdTE4o=,tag:2j/AKGvhp3VHFkSiu35BsQ==,type:str]
    APPLICATION_PASSWORD: ENC[AES256_GCM,data:leJFCyEb27H9iw==,iv:CqfX0VuED5ckLqBvVPfH/Yje6aVlEAVNkUkrL7Tp33M=,tag:4oux+hiYGzUnAXjEX3LFbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTHZMK3NTRFhUbUNQK0w5
            ZjU0azJUb2ZpaFlDbzFDRDZpaHBySGZodVdzCjQxY0NVWUZpRnIzMlNGSFZnNmNn
            a0VMaDJNMmJDdG92SVZva0cwV2ZjWmsKLS0tIDhPSHAvRW9IMlk4OWVDV0ozcmhr
            RSs5c0E2QU5rcWMvNVI3b094aUdKME0K7i3qz023Jq/eMWfVJbmKAfVnFZShWryf
            SJEatNaU4HYjFoAmRgUhYqNtH5pdKwbq1fn2CAttLixORkbdwhcI7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-16T09:29:46Z"
    mac: ENC[AES256_GCM,data:Ak8vmipd0u7i9wH8gOa7+aPDjjAg8Bb12lEZFXIcEJizPyaXFzKt6nvWwI4514hhngQ4wFbYlHJBZgzbCyN++DIAZruAgbkMfj3N91KkZjnZAMYzUt0S7Ny9TTPLOQwryvZCAEL8PfB4QTcfFPalxf6ObchecMQJoIDE1dyy5sM=,iv:BrPFOj6csG7Vd0ebyM6hppKUheG1lqINS9uqqaYTwy4=,tag:UHo8YL0a7WXmoPvupmjRVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
