apiVersion: v1
kind: Secret
metadata:
    name: pod-gateway-secret
    namespace: vpn
stringData:
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:VBnijDI=,iv:KRtVGEejSIVK+MdfiYMa9QywXZCkO45sa2CQyTT3rrI=,tag:yN+uxVdSEG+jGAWPCniqnQ==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:L0P+Q9TdAMQ6etu1fr0=,iv:2d+ILt2TnLPUDew2oOtxa9f6VfsUhHjdJrUPuNsQeF0=,tag:yiRfwIKF95M9sTVdbaBmtQ==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:RYYSWgsCm1RLzDvh4Cg=,iv:wXsdRbPx8vZsU6LNW8kBwCWMKbFm7nYikQUeqtLOAsM=,tag:4RvT/pZobbhhfqfHt1EPrA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:5A0UIZAnFpyBTGgekjNUTCyWLOc20zgjmlNeo5Xkfpk5uB+ODmneOKulw8o=,iv:CWJ0JXR7pKKVEnBlPMyLnD5RRwWuG+8w5VwiDlFFFVk=,tag:7HQoHOGF1FchdlyWI2HHTw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:t7g51nfGf+J7MvsFgzzOwS7WrtctpSsCtzSc0t3F/bWaIW8+5qpUjtL8on0=,iv:QUZiUZCUs7/ZysVouF78lT93uqWEA1Ni8g2dR3eerfM=,tag:4xkuDk32OXghL9+e9q+M5g==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:JXvpO8WoF1LYt7o=,iv:NWjvvnwBBe5Pqp2NZsTZqtzgQGC2lO20A0f6N05YGyc=,tag:xTOC0HaROq0ofzGRi8h1BQ==,type:str]
    VPN_DNS_ADDRESS: ENC[AES256_GCM,data:y9P1/Cq635s=,iv:rDUu78ILO5oQ7LEoWxD6dTi2gof6OzLKe6e8XW5sXok=,tag:fznQfKaTuBJS6cPotdMTFw==,type:str]
    VPN_PORT_FORWARDING: ENC[AES256_GCM,data:gT8=,iv:T091u8EleERiZ0+/6LuTexsyjg9rwPRdHIxFJj4GSUs=,tag:Vj0FKBKL1YLmSgkT0Io0eA==,type:str]
    VPN_PORT_FORWARDING_PROVIDER: ENC[AES256_GCM,data:A+s5+HuwvXKa,iv:GDPtZHCXc2Obw/PaLO4H/lpGX4IPTZaTv8ZFCBYi6rY=,tag:ujsjxj+GO7Sset5G0msDjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13p9s7k5su7ns4ys54qfj2cn2kekcv0h0jxg2hdgl68cy9yajvauqk82apf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOVlMTUIvTlc5bm1WZmJF
            bEZpUFRlR1gyVERXL01tN3ZBNVI2YnRKK0dVCjhidFE4U0syNHVaeDZkUk5BV3lh
            TzFuWE9MaFUwTXlheDQrM1RTdUMwajgKLS0tIHBPTmEwS0FmQjZWbzdseDBOYTgr
            SlFxUVZBNmpCL1hpWUhCRWQwVm45SGMKMh1wdeAQLhN/jETl1y/EwStlOOOJo/Pc
            xWWanSp6d+LgekF+5gDpMzre5U5rktoyrqEjRzrRCI0YIubSh+R4uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-26T10:41:33Z"
    mac: ENC[AES256_GCM,data:vCRlFJBjHoaBpihB1vto9GVXQ5pbyaDWzWvtaL/SF0imxNh4FWbwhCLpJzFm4tm7xfbqEdGiMljmvZFjcAwYYpcCJDeoetv1cLPBu9jteHO1um2a9YQ2123tVqN/Q+lUFiKcIeXxH/ghzkYYEgfxr9tkIKLHoLi4M7NFMrVyonQ=,iv:DqYWzSNfuRq2vRhbGRbeFplR3GTh5ENtVdxRM5wxKfA=,tag:PLlL4Iq9SkQiVgzJVxv6FA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
