---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-gateway-port-forward
  namespace: vpn
  labels:
    app.kubernetes.io/name: &name pod-gateway-protonvpn
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: ceph-block
