---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truenas-media-movies
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: truenas-media-movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truenas-media-tv
  namespace: media
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: truenas-media-tv
