---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 5.8.3.8933@sha256:da6094f6cc4dc95af194612a8a4d7db4fc27ff4a6e5748c2e6d5dd7be9ed69a7
    env:
      RADARR__INSTANCE_NAME: &name Radarr
      RADARR__PORT: &port 8080
      RADARR__APPLICATION_URL: "https://radarr.${SECRET_DOMAIN_LOCAL}"
      RADARR__LOG_LEVEL: info
    envFrom:
      - secretRef:
          name: radarr-secret
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: *name
          hajimari.io/icon: mdi:filmstrip
        hosts:
          - host: &host radarr.${SECRET_DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
        mountPath: /config
      media:
        enabled: true
        existingClaim: truenas-data-all
        mountPath: /data
    podAnnotations:
      secret.reloader.stakater.com/reload: radarr-secret
      backup.velero.io/backup-volumes-excludes: media
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        memory: 2000Mi
