---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: k8tz
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: k8tz
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: k8tz
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    labels:
      velero.io/exclude-from-backup: "true"
    kind: DaemonSet
    timezone: America/Los_Angeles
