---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: matter-server
  namespace: home
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/home-assistant-libs/python-matter-server
      tag: 5.5.3@sha256:8d2aca6b7cb97061e7f16a64a634f7cacf485ef63a49373d5423924d072a4524
    controller:
      type: statefulset
    service:
      main:
        ports:
          http:
            enabled: false
          websocket:
            enabled: true
            port: 5580
    hostNetwork: true
    persistence:
      config:
        enabled: true
        retain: true
        mountPath: /data
        size: 1Gi
        storageClass: ceph-block
