---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: matter-server
  app.kubernetes.io/instance: matter-server
generatorOptions:
  disableNameSuffixHash: true
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
