---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atuin-database-pvc
  labels:
    app.kubernetes.io/name: atuin-database-pvc
    app.kubernetes.io/part-of: atuin
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atuin-config-pvc
  labels:
    app.kubernetes.io/name: atuin-config-pvc
    app.kubernetes.io/part-of: atuin
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
