---
apiVersion: v1
kind: Service
metadata:
  name: atuin-svc
  labels:
    app.kubernetes.io/name: atuin-svc
    app.kubernetes.io/instance: atuin
spec:
  type: LoadBalancer
  ports:
    - name: ""
      port: 8888
  selector:
    app.kubernetes.io/instance: atuin-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atuin
  annotations:
    external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
    hajimari.io/enable: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: &host "atuin.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atuin
                port:
                  number: 80
  tls:
    - hosts:
        - *host
