---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: node-problem-detector
      version: 2.3.13
      sourceRef:
        kind: HelmRepository
        name: deliveryhero
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
